```properties
spring.application.name=study-api
server.port=8080

springdoc.swagger-ui.path=/
api.version=v1

# Database
# Quando a API está em um container e o MySQL está no host,
# use host.docker.internal como DB_SERVER_URL.
spring.datasource.url=jdbc:mysql://${DB_SERVER_URL:host.docker.internal}:${DB_SERVER_PORT:3306}/${DB_SCHEMA:study}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PWD:root_pwd}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
```
