name: Continuous Delevery

on:
    push: 

jobs:

    push_to_docker_hub:
        runs-on: ubuntu-latest
        steps:
            -   name: Imprimir imagem
                run: echo "Olá mundo"
            -   name: Step 2
                run: |
                    echo "Nova instrução"
                    ls